### ISSUE TITLE
I'm having trouble running this program.

### ISSUE THREAD

**Issue by mooritech** [pricklygorse/Interactive-Image-Background-Remover#2]
Thank you for making a wonderful program, but I am having a hard time running this program.

I saved some of the models and ran this program using vscode, but as soon as I loaded the image, I found the program stopped.

Do I need to add something file or package?

I have attached the error log below.

PS C:\works\Interactive-Image-Background-Remover-main> & C:/Users/000/AppData/Local/Microsoft/WindowsApps/python3.10.exe c:/000/Interactive-Image-Background-Remover-main/backgroundremoval.py
No arguments were given
EXIF data found
SAM models found: mobile_sam mobile_sam.encoder.quant.onnx sam_vit_b_01ec64 sam_vit_b_01ec64.decoder.quant.onnx sam_vit_b_01ec64.encoder.quant.onnx sam_vit_h_4b8939 sam_vit_h_4b8939.decoder.quant.onnx sam_vit_h_4b8939.encoder.quant.onnx sam_vit_h_4b8939.encoder_data.bin sam_vit_l_0b3195 sam_vit_l_0b3195.decoder.quant.onnx sam_vit_l_0b3195.encoder.quant.onnx
Whole image models found: BiRefNet-general-epoch_244
Traceback (most recent call last):
  File "c:\works\Interactive-Image-Background-Remover-main\backgroundremoval.py", line 2026, in <module>
    app = ImageClickApp(root, file_path)
  File "c:\works\Interactive-Image-Background-Remover-main\backgroundremoval.py", line 113, in __init__
    self.mask = Image.new("L", (int(self.orig_image_crop.width),
AttributeError: 'ImageClickApp' object has no attribute 'orig_image_crop'

**Comment by pricklygorse** [comment]
What operating system are you using? I've only tested on Linux, which I had to workout some issues with maximising the window.

Does un-commenting line 110 (remove the # from the start) fix it?

**Comment by mooritech** [comment]
I'm using Win10. 

When I deleted that comment, the first screen finally ran normally. I'll try to write more. Thank you.
